/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import java.security.NoSuchAlgorithmException;

public class NumberGeneratorTest {
    @Test
    public void shouldGenerateWords() {
        NumberGenerator generator = new NumberGenerator();
        try {
            generator.generate(6);

        } catch (NoSuchAlgorithmException e) {

        }
    }
}
